places = ['Tokyo', 'Italy', 'Greece', 'California', 'South Carolina']
print("Here is the original list:")
print(places)
print("\nHere is the sorted list:")
print(sorted(places))
print("\nHere is the original list again")
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)